services:
    camaleao-app:
        container_name: camaleao-app
        build:
            context: ./docker/php
        restart: unless-stopped
        volumes:
            - ./:/var/www
            - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        networks:
            - camaleao-network

    camaleao-server:
        container_name: camaleao-server
        restart: unless-stopped
        image: nginx:1.27.0-alpine
        ports:
            - ${FORWARD_APP_PORT:-8000}:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d/
        networks:
            - camaleao-network

    camaleao-mysql:
        image: mysql:5.7
        container_name: camaleao-mysql
        restart: unless-stopped
        volumes:
            - camaleao-mysql:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=${DB_DATABASE:-camaleao_web}
            - MYSQL_PASSWORD=${DB_PASSWORD:-secret}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-secret}
        ports:
            - ${FORWARD_DB_PORT:-3306}:3306
        networks:
            - camaleao-network

networks:
    camaleao-network:
        driver: bridge

volumes:
    camaleao-mysql:
